server:
  port: 8764
spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nameRoot
          uri: lb://eureka-client
          predicates:
            - Path=/name/**
          filters:
            - StripPrefix=2
        - id: add_request_parameter_route
          #       uri: http://localhost:9000
          uri: lb://producer
          filters:
            - AddRequestParameter=foo, bar
          predicates:
            - Method=GET
        - id: requestratelimiter_route
          uri: lb://producer
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                key-resolver: "#{@userKeyResolver}"
          predicates:
            - Method=GET
        - id: hystrix_route
          uri: lb://producer
          predicates:
            - Path=/consumingserviceendpoint
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/incaseoffailureusethis
        - id: retry_test
          uri: lb://producer
          predicates:
            - Path=/retry
          filters:
            - name: Retry
              args:
                retries: 3
                statuses: BAD_GATEWAY
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/











logging:
  level:
    org.springframework.cloud.gateway: debug
